### PR TITLE
Removed some Dead Links

### PR DESCRIPTION
**Pull request by kl1010**
Some of the dead links have been removed.

It would be nice to use [https://oembed.com/providers.json] as the provider source

### CODE REVIEW

**Comment by coleifer** [comment]
There are conflicts, can you rebase into a single patch? I'd be happy to merge.

**Comment by EmilStenstrom** [comment]
@coleifer Ready to merge?

**Comment by coleifer** [comment]
I replaced with equivalent patch.

**Comment by EmilStenstrom** [comment]
@coleifer Thanks! <3

**Pull request closed without merging**
